# Generated by Django 5.0.6 on 2024-07-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('farmer', 'Farmer'), ('moderator', 'Moderator')], default='user', max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
