# Generated by Django 5.0.6 on 2024-07-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ecological_region', models.CharField(blank=True, choices=[('hill', 'Hill'), ('mountain', 'Mountain'), ('terai', 'Terai')])),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='provinces.province')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
