# Generated by Django 5.0.6 on 2024-07-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='districts',
        ),
    ]
